config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#home"

  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  scope :order_desc, ->{order created_at: :desc}
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: Settings.name_maximum}
  validate :picture_size

  private

  def picture_size
    return unless picture.size > Settings.size_picture.megabytes
    errors.add :picture, t("less_than")
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: Settings.name_size}
  validates :password, presence: true, length: {minimum: Settings.name_min}, allow_nil: true
  validates :email, presence: true, length: {maximum: Settings.name_max},
   format: {with: VALID_EMAIL_REGEX}, uniqueness: true, uniqueness: {case_sensitive: false}

  has_secure_password
  has_many :microposts, dependent: :destroy

  before_save :downcase_email

  class << self

    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end
  end

  def new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false unless remember_digest.present?
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update remember_digest: nil
  end

  def current_user? user
    self == user
  end

  def feed
    Micropost.where("user_id = ?", id).order_desc
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def logged_in_user
    return if logged_in?
      store_location
      flash[:danger] = t "please_log_in"
      redirect_to login_url
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build micropost_params

    if @micropost.save
      flash[:success] = t "Micropost_created"
      redirect_to root_url
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = t "Micropost_deleted"
    redirect_to request.referrer || root_url
  end
  
  private

    def micropost_params
      params.require(:micropost).permit :content, :picture
    end

    def correct_user
      @micropost = current_user.microposts.find_by id: params[:id]
      redirect_to root_url unless current_user.correct?
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      log_in user
      params[:session][:remember_me] == Settings.one ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = t ".invalid"
      render :new
    end
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id

      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home;
    return unless logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.order_desc.page(params[:page]).per Settings.feed_number
  end

  def help; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i(index new create)
  before_action :logged_in_user, only: %i(index edit update destroy)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: %i(destroy)

  def index
    @users = User.page(params[:page]).per Settings.pages_limit
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      log_in @user
      flash[:success] = t "success"
      redirect_to @user
    else
      flash[:danger] = t "danger"
      render :new
    end
  end

  def show
    @microposts = @user.microposts.order_desc.page(params[:page]).per Settings.microposts_number
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t "profile_updated"
      redirect_to @user
    else
      flash[:danger] = t "noww"
      render :edit
    end
  end

  def destroy
    flash[:success] = t "user_deleted"
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = t "please_log_in"
    redirect_to login_url
  end

  def correct_user
    redirect_to root_url unless current_user.current_user? @user
  end

  def load_user
    @user = User.find_by id: params[:id]

    return if @user.present?
    flash[:danger] = t "danger"
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = I18n.t("application.title")
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id

      return unless user&.authenticated? cookies[:remember_token]
      log_in user
      @current_user = user
    end
  end
  
  def logged_in?
    current_user.present?
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size = Settings.gravatar_size_default
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
  <small>
    <%= link_to t(".the"), "http://www.railstutorial.org/" %>
    <%= link_to t(".by"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), "https://www.railstutorial.org/book/sign_up" %></li>
      <li><%= link_to t(".contact"), "https://www.youtube.com/watch?v=cnOIfm7imwQ" %></li>
      <li><%= link_to t(".new"), "http://news.railstutorial.org/" %>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
            <%= t ".account" %> <b class="caret"></b>
          <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: Settings.name_fifty), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %></span>
    <%= image_tag micropost.picture.url if micropost.picture? %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
    <%= link_to t("micro_delete"), micropost, method: :delete, data: { confirm: "You sure?" } %>
  </span>
</li>

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>
<h1><%= t "Password_reset" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<h1>PasswordResets#new</h1>
<p>Find me in app/views/password_resets/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    <%= t "The_form_contains" %> <%= pluralize object.errors.count, t("error") %>.
    <%= t "form" %> <% pluralize(@user.errors.count, t("error")) %>.
  </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
  <% end %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with model: @micropost do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: t("compose") %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture">
      <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
    </span>
  <% end %>
  <script type="text/javascript">
  $("#micropost_picture").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert t("max_file");
    }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, Settings.size_five), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("view_profile"), current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide :title, t(".about") %>
<h1><%= t ".about"%></h1>

app/views/static_pages/help.html.erb
<% provide :title, t(".help") %>
<h1><%= t ".help" %></h1>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render "shared/feed" %>
  </div>
  </div>
<% else %>
<% provide :title, t(".home")%>
<div class="center jumbotron">
  <h1><%= t ".welcom" %></h1>
  <h2>
    <%= t ".this" %>
    <%= link_to "Ruby on Rails Tutorial", "http://www.railstutorial.org/" %>
  </h2>
  <%= link_to t(".sig"), signup_path , class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), "http://rubyonrails.org/" %>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
    <%= render "shared/error_messages", object: f.object %>
  
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

app/views/users/_user.html.erb
<ul>
  <li>
    <%= gravatar_for user, size: Settings.size_fifty %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user.current_user?(user) %>
    | <%= link_to t("delete"), user, method: :delete, data: {confirm: t("you_sure")} %>
    <% end %>
  </li>
</ul>

app/views/users/edit.html.erb
<% provide :title, t("edit_user") %>
<h1><%= t "update_your_profile" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("all_users") %>
<h1><%= t "all_users" %></h1>

<%= paginate @users %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render @users %>
  <% end %>
</ul>

<%= paginate @users %>

app/views/users/new.html.erb
<% provide :title, t("users.new.sign_up") %>
<h1><%= t "users.new.sign_up" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= render "form" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
  <section class="user_info">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= paginate @microposts %>
    <% end %>
  </div>
</div>